public class math {
    public static void main(String args[]){
       // int a=20;
        int b=10;
        double random=Math.random()*1000;
        int a=(int)random;
        //System.out.println("Max number is "+Math.max(a, b));
        // Will print random number between 0.0 to 1.0
        System.out.println("Random generated by math function "+Math.random());
        // For printing specific range random number
        System.out.println("Random generated by math function ");
        // Value of random num in integer
        System.out.println("Random number value in integer "+a);
    }
}
